title: Pinpoint Panda
baseURL: /
params:
  accent_color: green
  color_scheme: light
  footer:
    content: '&copy; Pinpoint Panda Ltd. All rights reserved.'
    has_social: true
    links:
      - new_window: true
        text: Made with Stackbit
        url: 'https://www.stackbit.com'
  header:
    has_nav: true
    title: Pinpoint Panda
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
